WebApplication3/Areas/Admin/Controllers/LoginAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Areas.Admin.Controllers
{
    public class LoginAdminController : Controller
    {
        // GET: Admin/LoginAdmin
        private DAPMEntities database = new DAPMEntities();
        // GET: ADmin
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(AdminUser ad)
        {
            if (ModelState.IsValid)
            {
               
                if (string.IsNullOrEmpty(ad.NameUser)) ModelState.AddModelError(string.Empty, "Name không được để trống");
                if (string.IsNullOrEmpty(ad.RoleUser)) ModelState.AddModelError(string.Empty, "Role không được để trống");
                if (string.IsNullOrEmpty(ad.PasswordUser)) ModelState.AddModelError(string.Empty, "Password không được để trống");
                //Kiểm tra xem có người nào đã đăng kí với tên đăng nhập này hay chưa
                var admin = database.AdminUsers.FirstOrDefault(k => k.NameUser == ad.NameUser);
                if (admin != null) ModelState.AddModelError(string.Empty, "Đã có người đăng kí tên này");
                if (ModelState.IsValid)
                {
                    database.AdminUsers.Add(ad);
                    database.SaveChanges();
                }
                else
                {
                    return View();
                }
            }
            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(AdminUser ad)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(ad.NameUser)) ModelState.AddModelError(string.Empty, "Name không được để trống");
              
                if (string.IsNullOrEmpty(ad.PasswordUser)) ModelState.AddModelError(string.Empty, "Password không được để trống");
                if (ModelState.IsValid)
                {
                    // tim khach hang co ten dang nhap va password hop le trong csdl
                    var admin = database.AdminUsers.FirstOrDefault(k => k.NameUser == ad.NameUser && k.PasswordUser == ad.PasswordUser);
                    if (admin != null)
                    {
                        ViewBag.ThongBao = " chuc mung ban dang nhap thanh cong";
                        //luu vao session
                        Session["TaiKhoan"] = admin;
                        return RedirectToAction("Index", "MainAdmin", "Admin");
                    }
                    else
                    {
                        ViewBag.ThongBao = " ten dang nhap hoac mat khau khong dung";
                    }
                }
            }
            return View("Login");
        }
        [HttpGet]
        public ActionResult LogOut()
        {
            Session.Remove("TaiKhoan");

            return RedirectToAction("Index", "MainAdmin","Admin");
        }
    }
}

WebApplication3/Areas/Admin/Views/LoginAdmin/Login.cshtml
@model WebApplication3.Models.AdminUser

@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayOutADMIN.cshtml";
}



<div style="margin-left: 300px; width: 40%;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <h4 style="margin-left: 10px; font-family: 'Times New Roman', Times, serif; color: black;">Login</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameUser, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NameUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordUser, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.PasswordUser, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.PasswordUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Đăng nhập " class="btn btn-primary " />
            </div>
        </div>
    }

    <div class="container text-center mt-3 " style="margin-left: -257px; margin-top: -23px;">
        <a href="@Url.Action("Register", "LoginAdmin")" class="btn btn-secondary">REGISTER</a>
    </div>
</div>

WebApplication3/Areas/Admin/Views/LoginAdmin/Register.cshtml
@model WebApplication3.Models.AdminUser

@{
    ViewBag.Title = "Register";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayOutADMIN.cshtml";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container" style="width:70%; margin-left:400px;">
        <h4 style="margin-left:10px; font-family: Georgia;">Đăng ký tài khoản </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row"style="width:40%;background-color:whitesmoke">
            <div class="col-md-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label", style = "font-family: Georgia;" })
                    <div>
                        @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0", style = "font-family: Georgia;" } })
                        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NameUser, htmlAttributes: new { @class = "control-label", style = "font-family: Georgia;" })
                    <div>
                        @Html.EditorFor(model => model.NameUser, new { htmlAttributes = new { @class = "form-control", style = "font-family: Georgia;" } })
                        @Html.ValidationMessageFor(model => model.NameUser, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.RoleUser, htmlAttributes: new { @class = "control-label", style = "font-family: Georgia;" })
                    <div>
                        @Html.EditorFor(model => model.RoleUser, new { htmlAttributes = new { @class = "form-control", style = "font-family: Georgia;" } })
                        @Html.ValidationMessageFor(model => model.RoleUser, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PasswordUser, htmlAttributes: new { @class = "control-label", style = "font-family: Georgia;" })
                    <div>
                        @Html.EditorFor(model => model.PasswordUser, new { htmlAttributes = new { @class = "form-control", style = "font-family: Georgia;" } })
                        @Html.ValidationMessageFor(model => model.PasswordUser, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group" style="text-align: center;">
                    <input type="submit" value="Đăng ký" class="btn btn-primary" />
                  
                </div>
            </div>
        </div>
    </div>
}